import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const rubik = Rubik({ subsets: ['latin'], weight: ['400', '500'] })

export const metadata: Metadata = {
  title: 'Bookmark',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <nav>
          <Navbar/>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          <Footer/>
        </footer>  
      </body>
    </html>
  )
}
